### ISSUE TITLE
Issue: ModuleNotFoundError When Reproducing the Paper - Missing Dataset Module

### ISSUE THREAD

**Issue by kangzejian1896** [jaron1990/Express4D#2]
Hello! I'm trying to reproduce the results from your paper, but I encountered some problems. Here are the details:

`File "./data_loaders/get_data.py", line 7, in <module>
    from data_loaders.Express4D.dataset import Express4D
ModuleNotFoundError: No module named 'data_loaders.Express4D.dataset'`

**Comment by jaron1990** [comment]
Fixed :)

**Comment by art2611** [comment]
Hello, thanks for the fix! Saddly, the inference still does not got through due to the Express4D dataset missing the .npy files: 

`
  File "/mnt/c/Users/ajosi/Dev/model_testing/Express4D/data_loaders/Express4D/dataset.py", line 74, in __init__
    self.mean, self.std = calculate_mean_std()
  File "/mnt/c/Users/ajosi/Dev/model_testing/Express4D/data_loaders/Express4D/calc_mean_std.py", line 27, in calculate_mean_std
    all_frames = np.vstack(tensors)
  File "/home/ajosi/miniforge3/envs/Express4D/lib/python3.10/site-packages/numpy/_core/shape_base.py", line 291, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate
`

Could you please update the drive or fix for the inference to go through with the minimal setup?

**Comment by jaron1990** [comment]
Did you download the dataset and moved it to dataset/Express4D? For me it seems like that should be the issue.
Please let me know if it fixes the problem,
Thanks

**Comment by art2611** [comment]
Yes I did the download and moved it to dataset/Express4D. The dataset download is only composed of .csv files with the rigs values, .txt files with the paired text descriptions and the train/test splits whereas for inference, the dataset class named Express4D calls calculate_mean_std function that itself is looking for .npy arrays in the dataset. It breaks if not finding those. 

Here is the part of the code that I am refering to: 
```  
for root, dirs, files in os.walk(data_dir):
    for fl in files:
        if '.npy' in fl:
            data = np.load(os.path.join(root, fl))
            tensors.append(data)
all_frames = np.vstack(tensors)
```

**Comment by jaron1990** [comment]
My bad! Didn't notice the dataset had no npy files. all files are now in the drive.
Thanks,
Yaron
